#!/bin/bash

# -------------------------
# configuration
# -------------------------
#DMENU_FN="chirufont-10,Noto Color Emoji-10"
DMENU_FN="Iosevka-10,Noto Color Emoji-10"
DMENU_NB="#0f0f0f"   # normal background
DMENU_NF="#f82323"   # normal foreground
DMENU_SB="#f82323"   # selected background
DMENU_SF="#0f0f0f"   # selected foreground
DMENU_PROMPT="=> "
DMENU_LINES=10

# -------------------------
# choose mode: dmenu_run or custom list
# -------------------------
if [ "$1" = "run" ]; then
	echo -e "LOG :: \$1 = \"run\"\n"
	echo -e "LOG :: . . .\n"
	dmenu_run -fn "$DMENU_FN" \
        	  -nb "$DMENU_NB" -nf "$DMENU_NF" \
                  -sb "$DMENU_SB" -sf "$DMENU_SF" \
                  -l "$DMENU_LINES" -p "$DMENU_PROMPT"
elif [ "$1" = "bmj" ]; then
	echo -e "LOG :: \$1 = \"bmj\"\n"
	echo -e "LOG :: . . .\n"
	bemoji
else
	echo -e "LOG :: Reading from stdin\n"
	echo -e "LOG :: . . .\n"
	dmenu -fn "$DMENU_FN" \
              -nb "$DMENU_NB" -nf "$DMENU_NF" \
              -sb "$DMENU_SB" -sf "$DMENU_SF" \
              -l "$DMENU_LINES" -p "$DMENU_PROMPT"
fi

